### ISSUE TITLE
关于当前 follow 机制的 bug

### ISSUE THREAD

**Issue by liuly0322** [USTC-iCourse/ustc-course#12]
https://github.com/USTC-iCourse/ustc-course/blob/dcfa83112f389416c1a9857f7b6b15eb04ac6604/app/views/home.py#L41

似乎是这里的逻辑 `query.join(Notification, Review.id == Notification.ref_obj_id)` 有一定缺陷

当前如果是对自己某条评课的回复， `Notification.ref_obj_id` 也是那条评课的 id, 而不是回复的 id

https://github.com/USTC-iCourse/ustc-course/blob/401f8205927d8a88d002e19bec1f0f4c89ae7d29/app/views/api.py#L89

所以这个对自己评论的通知也会被 filter 到，而且后面并不会被 filter 走，会导致最后渲染页面的时候出现问题

![图片](https://user-images.githubusercontent.com/77669094/160743476-9b6c6f92-a4a7-4c99-8f8d-b4ca4520b066.png)

如图，分页和总数统计都会出现问题

**Comment by liuly0322** [comment]
![图片](https://user-images.githubusercontent.com/77669094/160743617-fc1ac5b9-a056-4d8d-884a-551dfe7dfaea.png)

应该是把这些通知都 filter 上了

**Comment by liuly0322** [comment]
可以考虑 filter 时增加 `operation` 的判断

https://github.com/USTC-iCourse/ustc-course/blob/9527a0adef2db5cce24fa0542691e8bb1b2010d2/app/models/user.py#L264

https://github.com/USTC-iCourse/ustc-course/blob/9527a0adef2db5cce24fa0542691e8bb1b2010d2/app/models/notification.py#L30

仅仅评课是 review operation

https://github.com/USTC-iCourse/ustc-course/blob/9527a0adef2db5cce24fa0542691e8bb1b2010d2/app/views/review.py#L54

**Comment by liuly0322** [comment]
提交 pr 试图修复 https://github.com/USTC-iCourse/ustc-course/pull/13

**Comment by liuly0322** [comment]
Solved in a0bcfe0d814ee64319e4ae8dc59b39efcc6f9716

**Comment by bojieli** [comment]
抱歉刚看到 issue，根据 Notification 来生成关注的点评确实有一些问题，后来我们改成根据当前的关注情况实时生成关注的点评了，分成关注课程的点评和关注的人写的点评。
