### ISSUE TITLE
Feature request: delete account permanently

### ISSUE THREAD

**Issue by ononoki1** [USTC-iCourse/ustc-course#16]
考虑到用户的隐私权，能否增加删除账户的功能？

具体形式可以是：
- 个人设置页面增加相应按钮 (recommended)
- 通过发送邮件方式让管理员手动删除

**Comment by bojieli** [comment]
1. 删除账户之后点评是不是也跟着全部删除了？
2. 删除账户之后重新注册一个新账户的话，一切都重新来过，就当原来的账户没存在过？

**Comment by bojieli** [comment]
@ononoki1 现在评课社区增加了隐藏用户 profile 的功能，并且可以把现有点评改为匿名，你觉得是否可以替代删除用户的功能？
https://icourse.club/announcements/

**Comment by ononoki1** [comment]
我觉得不能。

即使隐藏 profile，用户数据（邮箱地址、所写的点评等）仍然保留在服务器上，与删除账户（permanently delete user's account info/comments/...）很不相同。

**Comment by bojieli** [comment]
删除用户的话，应该是需要彻底删除用户的所有点评、评论、头像、上传的文件、通知消息、用户信息等，不可恢复，因此非常危险，如果是被盗号了而做出删除用户的行为，将可能造成严重的后果。

是不是可以由用户在网站上点击删除用户，然后系统发送确认邮件，点击邮件中的确认链接来删除用户？这样只有可能邮箱被盗号才有可能误删除用户，这个概率就相对低了。

**Comment by ononoki1** [comment]
> 是不是可以由用户在网站上点击删除用户，然后系统发送确认邮件，点击邮件中的确认链接来删除用户？这样只有可能邮箱被盗号才有可能误删除用户，这个概率就相对低了。

That's great!

**Comment by ononoki1** [comment]
> 用户可以首先删除自己的所有点评，然后给 service@icourse.club 发邮件，请求管理员删除用户。管理员对于没有点评的用户，可以手动做销户动作，并且删除所有关联的信息。

也是可行方案。

**Comment by bojieli** [comment]
已经开发完成删除用户的功能，用户可以首先删除自己的所有点评，然后给 [service@icourse.club](mailto:service@icourse.club) 发邮件，请求管理员删除用户。
