### ISSUE TITLE
Feature request: auto show most recent term

### ISSUE THREAD

**Issue by liuly0322** [USTC-iCourse/ustc-course#19]
考虑到现在不公开每门课选课名单了，对于大部分（新加入的）用户而言，编辑新评课时默认展示最近的学期是更合理的策略？

现在写新点评中的某门课默认选择的学期往往不是最新学期，给后面看点评的人带来困扰

例如 [CSAPP的评课](https://icourse.club/course/6246/) 选择按时间排序可以看到很多人误选择了 2017 春季学期

**Comment by bojieli** [comment]
多谢报 bug，已经在这两个 commit 2b21ea1665b45fd802ae64d3dd0788d586263eca 8958fa774200ec8d1e22b4da5feb62a322adea23 中修复。

目前 “学过” 功能不是关联到用户，而是关联到学号的，这个设计不太合理。原因是没有绑定学号的时候，“学过” 课程都加入到了一个 “空学号” 了，显示的时候就认为是这个 “空用户” 学过这门课了。现在已经改成对未绑定学号的用户取消 “学过” 功能，不再关联到 “空学号”。后续会改成 “学过” 同时关联到用户和学号，这样新用户就可以使用 “学过” 功能了。
