### ISSUE TITLE
`import_course_all_semesters.py` 使用了错误的硬编码用户id

### ISSUE THREAD

**Issue by tiankaima** [USTC-iCourse/ustc-course#40]
最近在做一套类似的项目，过来参考了评课社区关于 `jw.u.e.c` 的抓取方式。

注意到 <https://github.com/USTC-iCourse/ustc-course/blob/5556d25dc9c32b8cb7836e1c1c6672521569570f/tests/import_course_all_semesters.py#L55-L61> 使用了硬编码 `4367`，这个字段是用户 id, 其他用户不会正确返回结果

但如果考虑到维护团队相对固定，这也许也是个可以忽略的问题。如果要解决，获取这一id的方案是 访问 `https://jw.ustc.edu.cn/for-std/program` 然后解析 302 的地址 `/for-std/program/info/<int:id>`

**Comment by bojieli** [comment]
原来这个 4367 是我自己的用户 ID 啊，我以为是什么别的意思……我把它改一改

**Comment by bojieli** [comment]
多谢，已经修了 https://github.com/USTC-iCourse/ustc-course/commit/a096bae29177cabe052bc2e5d9a2266004939660
