### ISSUE TITLE
HTML 注入问题

### ISSUE THREAD

**Issue by PRO-2684** [USTC-iCourse/ustc-course#48]
通过手工构造 POST 请求，可以绕过前端的编辑器，直接向服务器 POST HTML 代码。
经测试，无法注入脚本。不知道有没有潜在的安全隐患。

**Comment by taoky** [comment]
CKEditor 在设计上就是存 HTML 代码的，所以需要服务端 sanitize，对应的代码在：https://github.com/USTC-iCourse/ustc-course/blob/eaeab35738b61bae3583dd999d956245c57ae484/app/utils.py#L122-L130

**Comment by PRO-2684** [comment]
> CKEditor 在设计上就是存 HTML 代码的，所以需要服务端 sanitize，对应的代码在：
> 
> https://github.com/USTC-iCourse/ustc-course/blob/eaeab35738b61bae3583dd999d956245c57ae484/app/utils.py#L122-L130

既然设计上就是 HTML, 那是否可以提供一个直接提交 HTML 代码的入口呢，目前这个编辑器缺少了一些我所需的内容

另外，这一行是 typo 吗，怎么有两个 height 🤔

https://github.com/USTC-iCourse/ustc-course/blob/eaeab35738b61bae3583dd999d956245c57ae484/app/utils.py#L129

**Comment by taoky** [comment]
> 既然设计上就是 HTML, 那是否可以提供一个直接提交 HTML 代码的入口呢，目前这个编辑器缺少了一些我所需的内容

是能加的，对应的是 <https://ckeditor.com/docs/ckeditor5/latest/features/source-editing.html>，之后会找个时间看看加上。

> 另外，这一行是 typo 吗，怎么有两个 height 🤔
> 
> https://github.com/USTC-iCourse/ustc-course/blob/eaeab35738b61bae3583dd999d956245c57ae484/app/utils.py#L129

是 typo，我之后交 PR 改。

**Comment by taoky** [comment]
> 目前这个编辑器缺少了一些我所需的内容

@PRO-2684 我试了一下加代码编辑模式，但是发现编辑器不认识的 HTML tag 会被编辑器自己 sanitize 掉 (<https://ckeditor.com/docs/ckeditor5/latest/features/source-editing.html#support-for-various-html-elements>)，所以单独加这个插件可能解决不了问题，需要再加上其他的插件。

可以说一下更具体的需求吗？我会优先考虑用编辑器自己的插件是否能够满足需求。

**Comment by taoky** [comment]
好像没有非常简单的办法可以处理（自己改 id 的话考虑到不同评论之间的冲突问题，后端需要额外加代码介入；`<details>` 和 `<summary>` 目前 CKEditor 5 还没有实现），我准备开个新 issue 以后续讨论。
