### ISSUE TITLE
评课评论（ReviewComment）中被尖括号包裹的内容会被删除

### ISSUE THREAD

**Issue by taoky** [USTC-iCourse/ustc-course#8]
例子：<https://icourse.club/course/6242/#review-43615> 中我的评论

<img width="706" alt="image" src="https://user-images.githubusercontent.com/2109893/159469373-cc3e8585-5438-4c41-8da4-1046c60d9196.png">

其中括号里的内容是 `<http://jyywiki.cn/OS/2021/>`（这也是 Markdown 的 [CommonMark 标准中的 link destination 语法](https://spec.commonmark.org/0.30/#link-destination)），我自己习惯这么写，因为用尖括号分割之后不会得到与预期不符合的超链接。

但是该内容会被 api.py 中的 `Markup(content).striptags()` 删除：

https://github.com/USTC-iCourse/ustc-course/blob/8e8b0b481352b437564667bfb03bc4a3661c7711/app/views/api.py#L73-L96

删除标签当然是为了防止被 XSS 的考虑，但是或许用 [`Markup.escape`](https://tedboy.github.io/flask/generated/generated/flask.Markup.html) 来清理用户输入更合适？

**Comment by bojieli** [comment]
不错，确实是个 bug，我应该用 Markup.escape 更合适

**Comment by bojieli** [comment]
done
